apiVersion: apps/v1
kind: Deployment
metadata:
  name: schedule-servicedeployment
  namespace: shankar
spec:
  replicas: 1
  selector:
    matchLabels:
      component: scheduleservice
  template:
    metadata:
      labels:
        component: scheduleservice
    spec:
      containers:
        - name: publishservice
          image: dockershankar/scheduleservicetest:${DOCKER_TAG}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
          resources:
            limits:
              memory: 200Mi
              cpu: 100m
            requests:
              memory: 150Mi
              cpu: 100m
      imagePullSecrets:
        - name: regcred

---

apiVersion: v1
kind: Service
metadata:
  name: scheduleservice
  namespace: shankar
spec:
  type: NodePort
  selector:
    component: scheduleservice
  ports:
    - port: 80
      nodePort: 30148
      targetPort: 80
