using System;
using System.Collections.Generic;
using System.Text;

namespace Scheduleservice.Core.Entities
{
    public class ClientsEntity
    {
        public int CLIENT_ID { get; set; }
        public int HHA { get; set; }
        public string PATIENT_ID { get; set; }
        public string SALUTATION { get; set; }
        public string FIRST_NAME { get; set; }
        public string MIDDLE_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string GENDER { get; set; }
        public int ADDRESS { get; set; }
        public string SSN { get; set; }
        public string MEDICARE_NO { get; set; }
        public string MEDICAID_NO { get; set; }
        public DateTime DATE_OF_BIRTH { get; set; }
        public int ETHINICITY_FLAG { get; set; }
        public int PAYMT_SRCS_FLAG { get; set; }
        public string OTHER_SRCS { get; set; }
        public int CASE_MANAGER { get; set; }
        public string STATUS { get; set; }
        public string DL_NO { get; set; }
        public int INTAKE_ID { get; set; }
        public string DRIVING_DIRECTIONS { get; set; }
        public int ATTENDING_PHYSICIAN { get; set; }
        public int PRIMARY_CLINICIAN { get; set; }
        public string SHORT_NOTES { get; set; }
        public string LANGUAGE { get; set; }
        public string PHARMACY_NAME { get; set; }
        public string PHARMACY_PHONE { get; set; }
        public int PRIMARY_OT { get; set; }
        public int PRIMARY_ST { get; set; }
        public int PRIMARY_PT { get; set; }
        public bool VALIDFACETOFACE_EXISTS { get; set; }
        public string LastAssessmentType { get; set; }
        public DateTime LastStatusDate { get; set; }
        public bool isHightLighted { get; set; }
        public int HHA_BRANCH_ID { get; set; }
        public bool LatestAdmit { get; set; }
        public int AdmitNo { get; set; }
        public int ClientGroupNo { get; set; }
        public string ClientNotes { get; set; }
        public DateTime SOCDate { get; set; }
        public string AssessmentSequence { get; set; }
        public int PRIMARY_MSW_CLINICIAN { get; set; }
        public int PRIMARY_Aide_CLINICIAN { get; set; }
        public byte REFERRAL_SOURCE_TYPE { get; set; }
        public int PHYSICIAN_CONTACT_ID { get; set; }
        public int PRIMARY_CARE_PHYSICIAN_ID { get; set; }
        public int LOB_ID { get; set; }
        public int LOB_GROUP_NO { get; set; }
        public int ADMIT_SEQUENCE { get; set; }
        public DateTime UPDATED_TIMESTAMP_FOR_OFFLINE { get; set; }
        public DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public int DeletedBy { get; set; }
        public DateTime PatientDeletedOn { get; set; }
        public bool isSentBackToReferral { get; set; }
        public bool showCOPTab { get; set; }
        public int TreatmentAddressID { get; set; }
        public string MBI { get; set; }
        public bool isPDGM { get; set; }
        public bool isRAPEOEBilling { get; set; }
        public bool isRAPEOEBillingSecondary { get; set; }
        public bool isEnablespecialinstruction { get; set; }
        public string SpecialInstructions { get; set; }
        public int TypeofInstruction { get; set; }
        public bool IsinstructionshowinVisitNotes { get; set; }
        public int Coordinator1 { get; set; }
        public int Coordinator2 { get; set; }
        public int Coordinator3 { get; set; }
        public int CLIENT { get; set; }
        public string PHY_REASON_FOR_CONTACT { get; set; }
        public DateTime PHY_CONTACT_DATE { get; set; }
        public string PHY_REASON_FOR_VISIT { get; set; }
        public DateTime PHY_VISIT_DATE { get; set; }
        public string ASSISTING_ORGANIZATION { get; set; }
        public int FIRE_EMERGENCY_PREPAREDNESS { get; set; }
        public int STRUCTURAL_BARRIERS { get; set; }
        public int ENVIRONMENTAL_RISK { get; set; }
        public int SANITATION_HAZARD { get; set; }
        public string HOME_SAFETY_PLAN { get; set; }
        public bool ELIGIBILITY_VERIFIED { get; set; }
        public DateTime ELIGIBILITY_LAST_VERIFIED { get; set; }
        public int ELIGIBILITY_VERIFIED_BY { get; set; }
        public string MARITAL_STATUS { get; set; }
        public bool HOME_SAFETY_EVALUATION_DONE { get; set; }
        public int REFERRAL_PHYSICIAN { get; set; }
        public int OASIS_CLINICIAN { get; set; }
        public int DOC_RECEIVED { get; set; }
        public DateTime DOC_RECEIVED_ON { get; set; }
        public bool ASSESSMENT_COMPLETED { get; set; }
        public DateTime ASSESSMENT_COMPLETED_DATE { get; set; }
        public string INSURANCE_GROUPNO { get; set; }
        public bool NoHomeSafetyProb { get; set; }
        public bool IsMSP { get; set; }
        public bool IsChildCare { get; set; }
        public DateTime ReferralDate { get; set; }
        public DateTime PhysicianOrderedDate { get; set; }
        public DateTime LastROCDate { get; set; }
        public DateTime LastROCReferralDate { get; set; }
        public DateTime LastROCPhysicianDate { get; set; }
        public int PHYSICIAN_SECONDARY_1 { get; set; }
        public int PHYSICIAN_SECONDARY_2 { get; set; }
        public int PHYSICIAN_SECONDARY_3 { get; set; }
        public int HOSPITAL_ID { get; set; }
        public byte EMERGENCY_PREPAREDENESS { get; set; }
        public int SALES_PERSON { get; set; }
        public string ELIGIBLITY_NOTES { get; set; }
        public int PHARMACY_ID { get; set; }
        public DateTime DateLastSeenByDoctor { get; set; }
        public bool ISLONGTERCARE { get; set; }
        public string INPATIENT_FACILITIES { get; set; }
        public string RELIGION { get; set; }
        public bool OutcomeReviewed { get; set; }
        public bool InterventationReviewed { get; set; }
        public int QA { get; set; }
        public string Height { get; set; }
        public string Weight { get; set; }
        public bool Language_InterpreterNeeded { get; set; }
        public bool Language_NonVerbal { get; set; }
        public bool Language_SignLanguage { get; set; }
        public bool Orders_DoNotRequireABNOrder { get; set; }
        public bool OASIS_SUMMARY_ONLY { get; set; }
        public byte OASISEXPORT_REQUIRED { get; set; }
        public byte DefaultAssessmentType { get; set; }
        public string CARE_TYPE { get; set; }
        public string MOTHER_NAME { get; set; }
        public int MOTHER_AGE { get; set; }
        public int MOTHER_ADDRESS { get; set; }
        public string FATHER_NAME { get; set; }
        public int FATHER_AGE { get; set; }
        public int FATHER_ADDRESS { get; set; }
        public string CSHCN_NO { get; set; }
        public int EPISODE_DURATION { get; set; }
        public bool isBillingAddressDifferent { get; set; }
        public int BillingAddress { get; set; }
        public bool DoNotRequireMedicationReview { get; set; }
        public byte LivingSituation { get; set; }
        public string BillFirstName { get; set; }
        public string BillLastName { get; set; }
        public bool ClientPayBillingAddress { get; set; }
        public string Occupation { get; set; }
        public DateTime EligibilityLastDate { get; set; }
        public byte BillingAcuity { get; set; }
        public string CBSA { get; set; }
        public string TelephonyID { get; set; }
        public int TeamMasterID { get; set; }
        public int coSignStaff { get; set; }
        public string QuickBooksID { get; set; }
        public bool DiscardDoubleBook { get; set; }
        public bool Enable_EVV { get; set; }
        public DateTime LastMDVisitDate { get; set; }
        public DateTime NExtMDVisitDate { get; set; }
        public int PlaceOfService { get; set; }
        public bool overrideMedicationOption { get; set; }
        public char MedicationOptionType { get; set; }
        public int ICDCoder { get; set; }
        public string ContractReference { get; set; }
        public int ReferringPhysicianOffice { get; set; }
        public string NickName { get; set; }
        public string DischargeReasonBillingCode { get; set; }
        public bool enabledForSuppliesDataExchange { get; set; }
        public string EVVClientID { get; set; }
        public int AttendingPhysicianOffice { get; set; }
        public int PrimaryPhysicianOffice { get; set; }
        public string TransportationAssistanceLevel { get; set; }
        public string County { get; set; }
        public int Scheduler { get; set; }
        public bool DiscardDeviation { get; set; }
        public int CoderGroupMasterID { get; set; }
        public string CCDPatientHELCommunityID { get; set; }
        public bool doNotReadmitClientAfterDischarge { get; set; }
        public bool isDirtyWorldView { get; set; }
        public int WorldViewClientUniqueID { get; set; }
        public string DSCC_NO { get; set; }
        public bool IsHL7FieldsDirty { get; set; }
        public bool IsUpdatedToTissueAnalytics { get; set; }
        public string FIRE_EMERGENCY_PREPAREDNESS_New { get; set; }
        public string STRUCTURAL_BARRIERS_New { get; set; }
        public string ENVIRONMENTAL_RISK_New { get; set; }
        public string SANITATION_HAZARD_New { get; set; }
        public bool NotHaveRepresentative { get; set; }
        public bool NotToListRepresentative { get; set; }
        public bool IsSOCDateDirty { get; set; }
        public bool overrideSubformMandatoryForEchart { get; set; }
        public int MissedVisitOrderClinician { get; set; }
        public string SupplyDataExchangeMethods { get; set; }
        public string EVVPatientRegion { get; set; }
        public string EVVPatientSDA { get; set; }
        public DateTime locationEffectiveFrom { get; set; }
        public bool HHAExchangeInvolved { get; set; }
        public string PrimaryEvvVendorID { get; set; }
        public string SecondaryEvvVendorID { get; set; }
        public bool Isnewborn { get; set; }
        public string PayrollExportID { get; set; }
        public bool isOrdersReceived { get; set; }
        public bool EvvMissedVisitContingency_isAttested { get; set; }
        public DateTime EvvMissedVisitContingency_AttestedUIDate { get; set; }
        public string ADMISSION_TYPE { get; set; }
        public string STATE_CM { get; set; }
        public int STATE_CM_ADDRESS { get; set; }
        public byte SUPER_VISION_PLAN { get; set; }
        public string ASSISTIVE_DEVICES { get; set; }
        public string SPECIAL_EQUIPMENT { get; set; }
        public string SPECIAL_EQUIPMENT_OTHER { get; set; }
        public string Living_With { get; set; }
        public string Living_Support { get; set; }
        public string Living_HomeSafetyPlan { get; set; }
        public string Homebound_Reason { get; set; }
        public bool isImportedPatient { get; set; }
        public bool SMSEnabled { get; set; }
        public bool overrideClientMaxHoursPerWeek { get; set; }
        public float ClientMaxHoursPerWeek { get; set; }
        public bool ClientMaxHoursPerWeek_isHardStop { get; set; }
        public DateTime HomecarePulseLastUpdatedOn { get; set; }
        public bool isInfectionControlTrainingDone { get; set; }
        public string InfectionControlTrainingNote { get; set; }
        public bool InfectionControlTrainingProvidedToPatient { get; set; }
        public int InfectionControlTrainingReceivedCaregiver { get; set; }
        public string InfectionControlTrainingReceivedOther { get; set; }
        public bool isMedicationTrainingDone { get; set; }
        public string MedicationTrainingNote { get; set; }
        public bool MedicationTrainingProvidedToPatient { get; set; }
        public int MedicationTrainingReceivedCaregiver { get; set; }
        public string MedicationTrainingReceivedOther { get; set; }
        public bool isCareManagementTrainingDone { get; set; }
        public string CareManagementTrainingNote { get; set; }
        public bool CareManagementTrainingProvidedToPatient { get; set; }
        public int CareManagementTrainingReceivedCaregiver { get; set; }
        public string CareManagementTrainingReceivedOther { get; set; }
        public int CMAAgencyID { get; set; }
        public bool PaymentMethodsEnabled { get; set; }
        public int PaymentGatewayId { get; set; }
        public string PaymentMethodCustomerKey { get; set; }
        public int CDSEmployerID { get; set; }
        public int FMSAVendorID { get; set; }
        public int TASVendorID { get; set; }
        public DateTime POCDiscussedOn { get; set; }
        public int POCDiscussedBy { get; set; }
        public bool isPhysicianContacted { get; set; }
        public int DSAVendorID { get; set; }
        public int CMAVendorID { get; set; }
        public int SFSVendorID { get; set; }
        public string EVVCCUContractNumber { get; set; }
        public string CPRCode { get; set; }
        public string DischargeNotes { get; set; }
        public bool Notifyd_Enabled { get; set; }
        public string Notifyd_uid { get; set; }
        public bool Notifyd_IsAuthorized { get; set; }
        public bool Notifyd_IsExpired { get; set; }
        public DateTime Notifyd_EnabledOn { get; set; }
        public int FrontStreamConfigId { get; set; }
        public bool Enable_Payment_Notification { get; set; }
        public bool NotifyByMail { get; set; }
        public string PrimaryNotificationMailID { get; set; }
        public string SecondaryNotificationMailID { get; set; }
        public bool NotifyByFax { get; set; }
        public string Fax { get; set; }
        public bool EnableCreditCardNotification { get; set; }
        public bool Notifyd_AssociationDone { get; set; }
        public string CDSEvvVisitMaintenanceResponsibleParty { get; set; }
        public DateTime CDSEvvVisitMaintenanceEffectiveFrom { get; set; }
    }
}
